apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: backend
    group: com.mammutmkii.clcproject
    provider: fabric8
    version: 0.0.1-SNAPSHOT
  name: backend
  namespace: clcproject
spec:
  lookupPolicy:
    local: true