apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: backend
    group: com.mammutmkii.clcproject
    provider: fabric8
    version: 0.0.1-SNAPSHOT
  name: backend-s2i
  namespace: clcproject
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'backend:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'fabric8/s2i-java:2.1'
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
