apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: stock-poller
  name: stock-poller
  namespace: clcproject
spec:
  backoffLimit: 100
  completions: 100
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: stock-poller
      name: stock-poller
    spec:
      containers:
        - command:
            - python
            - app.py
          image: 'docker-registry.default.svc:5000/clcproject/stock-polling'
          imagePullPolicy: Always
          name: stock-poller
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
